### ISSUE TITLE
Usage of String constant as property value

### ISSUE THREAD

**Issue by roelofkemp** [Dexels/navascript-editor#7]
Consider the code below, in particular the value of the property (written as a String constant):

```
message "Example" {
    property "Test" = "Test";
}
```

Executing this script gives the following output:
```
   <message name="Example">
      <property name="Test" type="string" value=" Test         " direction="in"/>
   </message>
```

Note the additional whitespace around Test, which should not happen

**Comment by aschoneveld** [comment]
Fixed this in _fb_navajo_issue_537
